version: "3"
services:
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      - [SOME_LOCAL_PATH]/db:/var/lib/mysql
    ports: 
     - 3307:3306
    environment:
      MYSQL_DATABASE: coffee-shop
      MYSQL_ROOT_PASSWORD: root
